using NUnit.Framework;

namespace AocSolutionsCSharp.Day02
{
    [TestFixture]
    public class Tests
    {
        [Test]
        public void StringComparer()
        {
            Assert.That(Solution.OnlyDifferInOneCharacter("abcde", "axcye"), Is.False);
            Assert.That(Solution.OnlyDifferInOneCharacter("fghij", "fguij"), Is.True);
        }

        [Test]
        public void FindCommonCharacters()
        {
            Assert.That(Solution.FindCommonCharacters("fghij", "fguij"), Is.EqualTo("fgij"));
        }

        [Test]
        public void Test()
        {
            Assert.That(Solution.Part1(testInput), Is.EqualTo(12));
        }

        [Test]
        public void TestPart2()
        {
            Assert.That(Solution.Part2(testInput2), Is.EqualTo("fgij"));
        }

        [Test]
        public void Part1()
        {
            Assert.That(Solution.Part1(input), Is.EqualTo(7776));
        }

        [Test]
        public void Part2()
        {
            Assert.That(Solution.Part2(input), Is.EqualTo("wlkigsqyfecjqqmnxaktdrhbz"));
        }

        private const string testInput2 = @"abcde
fghij
klmno
pqrst
fguij
axcye
wvxyz";

        private const string testInput = @"abcdef
bababc
abbcde
abcccd
aabcdd
abcdee
ababab";

        private const string input = @"wlpiogsvdfecjdqmnxakudrhbz
wbpioesvyfecjuqmlxaktdrhbz
blviogavyfecjuqmnxaktdrhbz
wlpiogsvydecjuqmnipktdrhbz
wlwiogsvyfmcjuqmoxaktdrhbz
wlpiogsvphecjuqmnxaktdrzbz
wlpiogsvyfecjuqmnkakhdrkbz
wlpiogsvyfhcjuqmnxxktddhbz
wlpiogsvyfccfuqmnxgktdrhbz
wlpiogsvhmecjvqmnxaktdrhbz
wlpiogsvyfecjdqqnxaktdrhyz
wlpiogyvycecjaqmnxaktdrhbz
wlpiogsvyfecjfqmnxaktybhbz
wkpiogsvyfmcauqmnxaktdrhbz
wlmiolsvyfecjuqmnxaktdrhbn
wlpioksvyfecjuqmnxaktdrhgs
wlpiogsvyflcjuvmnxsktdrhbz
wgziogsvyfecjuqmnxaktdrhoz
whpingsvyeecjuqmnxaktdrhbz
wlpiogsvyfecjuqgnxaktdvhlz
wlpioasvtfecjuqmnxaktdahbz
wlpihgsvefeceuqmnxaktdrhbz
wlpiogsvyfecyuqwnxaktdghbz
wlpfsgsvyfhcjuqmnxaktdrhbz
wlpiogyvyfecjuqmnxalpdrhbz
wlpiogsvyfescsqmnxaktdrhbz
wluiogsvyfecytqmnxaktdrhbz
wltiorsvyfecjuqmoxaktdrhbz
wlmiogwvyfejjuqmnxaktdrhbz
wlpiogsvyfycjuumnxvktdrhbz
wlkiogsqyfecjqqmnxaktdrhbz
wlpiogsvyfecouqmnxaktfrubz
hupiogsvlfecjuqmnxaktdrhbz
wlpiogsvpxecjuqmnxaksdrhbz
wlpiogsvyfkcjfqmnxxktdrhbz
wlpiogsjyfecjuqnnxakthrhbz
wlpiogsvyfecjuqmnxaktddhdk
wlpipgsvyfecjuqmnhaktdrubz
wlpiogsoyfenjpqmnxaktdrhbz
wlpiogsvyfecnuqmnxaxtdrmbz
wlpiggsvyfjcjuumnxaktdrhbz
wlppogsvyfecjuqmnxautdhhbz
wlpiovbvyfecjuqmnxaktcrhbz
wlpiogsvyfecjoqmnxaktdrobu
wlpiohsvyfecjugmnxakthrhbz
wvpiogovyfecjuqmnxakwdrhbz
wlpiogsbyfecjuqmnxdktdrtbz
wlpnogsvyfecjuqmnxakykrhbz
wlpiogpvyfecjuqmnxvktdrhbs
wlpiogsvkvecjuqmnxadtdrhbz
wlkihgsvyfecjuqmnxlktdrhbz
wlpilgsvyfhcjuqmnxakudrhbz
wlpioksvysgcjuqmnxaktdrhbz
wlpiogsvyfecorqmoxaktdrhbz
wlpiogsvyfectzlmnxaktdrhbz
wlpiogsvywecjuqwnqaktdrhbz
wlpiowsvyfecjuqrnxaftdrhbz
wlpiogsuyfecjutmnxaktnrhbz
wepiowsvyfqcjuqmnxaktdrhbz
wlpirgssyfecjuqmvxaktdrhbz
wlyiogstyfecjuqmnxaktdrhbw
wlpiogseyfecauqmnxaktdjhbz
wlpioisvyfenjuqmnxakrdrhbz
wlpiogsvyfrgjfqmnxaktdrhbz
wlpionsvyfecjmqmjxaktdrhbz
alpiggsvyfecjuqmnxaktdrhkz
wlphngsvyfecjuqmnxfktdrhbz
wlpiogsvyferjuqmlxakttrhbz
wlniogsvefecjuqsnxaktdrhbz
wlpiogsvyfncjurmnxakudrhbz
wlpiogsvyfecjuqmnxaktprlaz
wlpiocsvyfecjupmkxaktdrhbz
wlpihgsvyfecjeqfnxaktdrhbz
wlwioasvyfjcjuqmnxaktdrhbz
wlpifgsvyfecjuqsnxaktdshbz
wlxiogsvyrechuqmnxaktdrhbz
wlpiogovyfxcjuqmnxakkdrhbz
wlpiogsvyfecjkqmdxaktmrhbz
wlpiogsvyfecjwqmntaktdhhbz
wlpiogsvdfecjuqmmxaktbrhbz
wlpiogsvyfecauqmnxaksdrhwz
wlpiogsvwfecjuqznxaktorhbz
wlpiogtvyfecjuqhnxakidrhbz
wlpiogsvyyecjuqmnxaktdrhwt
wljiogsvyfecfuqbnxaktdrhbz
wlpiogsvybecjuqmnxagtdrjbz
wrpiogsvyfecjuqmnuaktdrhbd
wlpiogsvyfecjurmnxnltdrhbz
blpvogsvyaecjuqmnxaktdrhbz
bfpiogyvyfecjuqmnxaktdrhbz
wlpiogsvyfecjuqinxaknddhbz
wlpizgsvvfecjuqxnxaktdrhbz
glpiogsvyrecjuqmnxaktdrhbr
wlpiogskhfecjutmnxaktdrhbz
wlpiogsvyfecmuqmnxaktdribc
wlpioesvwfecjuqmnxakkdrhbz
wlpionsrafecjuqmnxaktdrhbz
wlsiogsvyfecjuqmnaaktdrhvz
bloiogsvyfecjuqmnxakjdrhbz
wlpiogsvyfecjuqenmastdrhbz
wlpiogyvyfecjuqmuxakldrhbz
plpiogovyfecjuvmnxaktdrhbz
wlpiogsvyfebjuqmnkakvdrhbz
wlziogsvyfhcjuqmngaktdrhbz
wlsiogsvyfecjuqmnxaktdrzjz
plbiogsvyfecfuqmnxaktdrhbz
wfpiogsvyfecjuqknxaktdrhiz
wlpiogjbyfecjuqmnxaktprhbz
wmpiogsvyrecjcqmnxaktdrhbz
wlpiogsyyfecjuqmqxaktdrbbz
wlpiogsvyfecjuqknxaetdehbz
wlpiogsvyfezjuqmnxakkdhhbz
wlpiogsvyfecjjqvnxaktdrhiz
wkpiogsvyfucjuqmnxaktdrhbd
lliiogsvyfecjuqmnxaktdrhoz
wlpiogsvyfecjuqmsxdktdshbz
wlprogtvyfecjuqmnxaktvrhbz
wlpizgssyffcjuqmnxaktdrhbz
wlpioasvyfvcjuqmnxakldrhbz
wlpoogsvyyecjuqmnxastdrhbz
wlpiognvyfecjuqmnsaktdrhbr
wlpiogsoyfecjuqmnxaktdrhho
wfpiogsvydecjuqmnxaotdrhbz
wlpiogsvqhecjuqmnxaktdrhhz
wkpiogsvyfeojuqmnxaktdrqbz
wlpiogsvyfeveuqmnxaktdshbz
wlpiogbvyfecjuqmexaktdrcbz
wlpxogsvyfehjsqmnxaktdrhbz
wlpcogsvyfecjuqmnjakttrhbz
wlpiogsvvkecjuqmnxaftdrhbz
wlpiogsvffecnuqmnxaktdnhbz
wlpiogsvyfecjupjnxaktdrhbr
wlpqogsvyfecjuqmnxlktdphbz
wlpxogsvyfecjvqmnxaktirhbz
elpiogsvyfecjuqlnxaqtdrhbz
wspiogsvrfecjuqmnxakadrhbz
wlpiogsmyfecbuqmnxactdrhbz
wlpiogsvyfecauqmnyakzdrhbz
wlsiogsvyfecjuqmnxakvdrnbz
wlpiogsxyfeijuqmnxakndrhbz
wlpiogsvyfecjuumnxakbyrhbz
wlpiogsvyfecjuqmnxhktdyhbo
wlpiogsvyfecjuqqnxnjtdrhbz
wapiogsvyfecjuqmnxoktdrmbz
wlpiogsvyfeejvqmnxaktdrubz
wlpitgsvyeectuqmnxaktdrhbz
alpiogsvyfecjulmnxaktdchbz
wlpiogsvyfecjuqmuxoktdrwbz
wlpiogsvyfzgjuhmnxaktdrhbz
wlpnogsvyfecjuqmdxaktyrhbz
wlpiogsvyfecjuqmnxakthrhra
wliiogsvyfecluqmnxaktdhhbz
wlpiogsvyfecjuymnxaltdrhwz
wlpiogsvyfeljuqmnxaktyrhbd
wlpiygsvvfecjuqmfxaktdrhbz
wlpiogihsfecjuqmnxaktdrhbz
wlpiogjvyfecjuqmnhuktdrhbz
wldiogsvyfecjiqmwxaktdrhbz
wlpiogsvjfecjuqmnxaktdrgbr
wlpioisvyfecjuqwnxabtdrhbz
wlviogsvyfscjuqmnxqktdrhbz
wlpiogsvyfecjuqmuxakbdrubz
wlpiogsvyfecjuqmnxmatdrhqz
wlpiogsvyfbcjuqwmxaktdrhbz
wlpiogsvyfexjuqmnxuxtdrhbz
wljiogsvbfecjuqmnxartdrhbz
wlpvogsvyfeujuqmnxaktdmhbz
wnpiogsvyfekjuqanxaktdrhbz
wlprogsvyfecjuqmzxvktdrhbz
wkpiogvvyfecjuqmnxaktdrabz
wlpiogsvwfecjuqmnxaktkbhbz
wlpiogsvyfecjlqmnxtttdrhbz
wlpioqsvyfecjuqznxaktyrhbz
wlpiogsvyfecjuqmnxnethrhbz
wlpiogsyyfgcjuqmnxaktdrhbm
wlpiopsvbfecjuqmnxaktdlhbz
wloqogsvyfucjuqmnxaktdrhbz
wlpiogsvmfecjuqmnxmktdrhtz
wlhiogsvyfecjuhmnxaktsrhbz
wlpioggvpfecjufmnxaktdrhbz
wlpiogsvyfbcjuomnxaktdrhbh
wlpmogsvyfecyuqmnxoktdrhbz
wlpiogslyfecjuqmnxaptyrhbz
tlpiogsnyfecguqmnxaktdrhbz
wlpiogsvyfecjuqmnxwktwehbz
wlpiogsvgfecjuqmnxaktdrabu
wbpiogsvyfecjuqmnxagtdrhoz
wlwipgsvyfecjuqmnxaktdrhbu
wlpwogsvykeczuqmnxaktdrhbz
wlpgogsvwfecjuqmnxcktdrhbz
wlpiogsqyfecjuqmrxaktdrrbz
wlpiogsvyfecjuqmnxakthrafz
wypicgseyfecjuqmnxaktdrhbz
wlpiogcvqfecjuqmnxaktdrhzz
wlriogsvyfecouqmnkaktdrhbz
wlpiogsvyfemjulmnxaktdrhdz
flpiogadyfecjuqmnxaktdrhbz
wupiogsvyfbvjuqmnxaktdrhbz
wlpiogsvyfebjummnxaktdrrbz
wjpiogsvyfecjuqmnxaktprybz
wlpirgsvyfecjiqmnxaatdrhbz
bvpiogsvyfecjuqmnxaktdrhez
wlpiogsvyfxcjuqmnxykzdrhbz
wlkiwgsqyfecjqqmnxaktdrhbz
wepaogsvyfecjxqmnxaktdrhbz
wlpiovsvyfecjjqmnxaktdmhbz
wlpioysryfecjuqmnxaktdrhiz
wlpizjsvyfecjuvmnxaktdrhbz
dlpiogsvyfecjucmnxakbdrhbz
wlpiogsccfecjrqmnxaktdrhbz
wlpioggvyfecpuqmnxagtdrhbz
wlpiogsvyfvcjuumlxaktdrhbz
wwpiogsryfjcjuqmnxaktdrhbz
wlpiogsvyfecjuqynxaktdrogz
wlpiogsvyfecjpqmnxskbdrhbz
wlpiogsvyfecjuhmfxaktvrhbz
wlpiogevyfecjrqmnwaktdrhbz
wlpiigsvyfemjuqmnxaktdrhtz
wlpcogsvyfecjuqhnxakgdrhbz
wupiogsvyfxcjuqmnxaktdrhgz
wlsiogsvyfecjuqenxuktdrhbz
wlpioglvyfecjujmexaktdrhbz
wlriogsvyfeljuqmnxattdrhbz
wlpiogsvyfecfuqmhxaktkrhbz
wlppogsvyfecjuqmxxabtdrhbz
wlniogsvyfevjuqwnxaktdrhbz
wlhiogsvyfecjuqmnxactxrhbz
ilpiogivyflcjuqmnxaktdrhbz
wlpmogsvyfecjuqmnxaktdrlbs
wipiogsvyfeqjuqmnxaktrrhbz
wvpiogsvyfecjuqknxaktdrrbz
wwpioguvyfecxuqmnxaktdrhbz
wlpiogsvkfdcjuqmnxaktdzhbz
wlpiogfvyfecjuqmnxadtdrhbg
wlpiogsvyzefjuqfnxaktdrhbz
wlpiogstyfechuqmnxaktdchbz
wlpiogszyfedjuqmnxsktdrhbz
wzpiozsvyfncjuqmnxaktdrhbz
xlpiogsvyfefjuqmnmaktdrhbz
wlpiogsvyfebxummnxaktdrhbz
wlpiogsgyfecfurmnxaktdrhbz
wlpqogsvyfecjuomnxaktdrhbi
wlpiogjvufecjuqmnxaktdrhbd
wlpiolsvyfecduqmnxaktrrhbz
wlpxogsvyfecjuqmnxaktgrhbk
wlpiogsfyfncjuqmnxsktdrhbz
wlpioggvyfecjufmnxaktdrebz
wlpiogsvyfecfujmnxaktdrwbz
rlpiogsvyfecjlqmnxaktdqhbz
wlpfogsvyfecjuimnxaktfrhbz";
    }
}
